name: Add publication (URL or DOI)
description:  |
  Add publication by URL or DOI. 
  
title: "[Add publication]"
labels: ["automatic-add-publication-by-id"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: >
        This form will automatically generate a PR that will be reviewed by the maintainers.

  - type: dropdown
    id: method
    attributes:
      label: Method
      description: Whether to use DOI or URL to add the publication.
      options:
        - DOI
        - URL
    validations:
      required: true

  - type: input
    id: identifier
    attributes:
      label: Identifier
      description: |
        One or more identifiers separated by ';'.
        DOI example: "10.1038/nphys1170" or "10.1038/nphys1170; 10.1093/poq/nfab012"
        URL example: "https://arxiv.org/abs/1904.1234"
        Accepted URL domains: semanticscholar.org, arxiv.org, aclweb.org, acm.org, biorxiv.org
      placeholder: "10.1038/nphys1170; 10.1093/poq/nfab012"
    validations:
      required: true


